/* ==========================================================================
   Catalog data
   Placeholder inventory reflecting the categories on the shop flyer
   (Smartphones, Laptops, Accessories, Watches, Audio). Once the admin
   backend is wired up, this array will be replaced by a live API call —
   the rendering code never assumes more than these fields, so swapping
   the data source later is a drop-in change.
   ========================================================================== */

const CATEGORIES = [
  { id: 'smartphones', name: 'Smartphones', icon: ICONS.devicePhone },
  { id: 'laptops', name: 'Laptops', icon: ICONS.deviceLaptop },
  { id: 'wearables', name: 'Watches', icon: ICONS.deviceWatch },
  { id: 'audio', name: 'Audio', icon: ICONS.deviceHeadphones },
  { id: 'accessories', name: 'Accessories', icon: ICONS.deviceEarbuds },
];

const PRODUCTS = [
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro 256GB',
    brand: 'Apple',
    category: 'smartphones',
    price: 1250000,
    wasPrice: 1350000,
    stock: 6,
    icon: ICONS.devicePhone,
    blurb: 'Titanium design with the A17 Pro chip, a 48MP main camera and an action button for quick shortcuts.',
    specs: [['Display', '6.1" Super Retina XDR'], ['Chip', 'A17 Pro'], ['Storage', '256GB'], ['Camera', '48MP triple camera'], ['Battery', 'Up to 23h video playback']],
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14 128GB',
    brand: 'Apple',
    category: 'smartphones',
    price: 780000,
    stock: 9,
    icon: ICONS.devicePhone,
    blurb: 'A reliable everyday flagship with a bright OLED display and all-day battery life.',
    specs: [['Display', '6.1" Super Retina XDR'], ['Chip', 'A15 Bionic'], ['Storage', '128GB'], ['Camera', '12MP dual camera'], ['Battery', 'Up to 20h video playback']],
  },
  {
    id: 'galaxy-s24',
    name: 'Samsung Galaxy S24',
    brand: 'Samsung',
    category: 'smartphones',
    price: 980000,
    stock: 5,
    icon: ICONS.devicePhone,
    blurb: 'A compact flagship with a sharp AMOLED display and Galaxy AI features built in.',
    specs: [['Display', '6.2" Dynamic AMOLED 2X'], ['Chip', 'Snapdragon 8 Gen 3'], ['Storage', '256GB'], ['Camera', '50MP triple camera'], ['Battery', '4000mAh']],
  },
  {
    id: 'galaxy-a55',
    name: 'Samsung Galaxy A55',
    brand: 'Samsung',
    category: 'smartphones',
    price: 420000,
    stock: 14,
    icon: ICONS.devicePhone,
    blurb: 'A dependable mid-range pick with a large display and long battery life for everyday use.',
    specs: [['Display', '6.6" Super AMOLED'], ['Chip', 'Exynos 1480'], ['Storage', '128GB'], ['Camera', '50MP triple camera'], ['Battery', '5000mAh']],
  },
  {
    id: 'tecno-camon-30',
    name: 'Tecno Camon 30',
    brand: 'Tecno',
    category: 'smartphones',
    price: 265000,
    stock: 20,
    icon: ICONS.devicePhone,
    blurb: 'A camera-focused mid-ranger with a curved display and fast charging for the money-conscious buyer.',
    specs: [['Display', '6.7" AMOLED curved'], ['Chip', 'MediaTek Helio G100'], ['Storage', '256GB'], ['Camera', '50MP OIS camera'], ['Battery', '5000mAh, 70W charging']],
  },
  {
    id: 'itel-s24',
    name: 'Itel S24',
    brand: 'Itel',
    category: 'smartphones',
    price: 145000,
    stock: 25,
    icon: ICONS.devicePhone,
    blurb: 'An affordable everyday smartphone with a big battery and a clean, easy-to-use interface.',
    specs: [['Display', '6.6" HD+'], ['Chip', 'Unisoc T606'], ['Storage', '128GB'], ['Camera', '50MP dual camera'], ['Battery', '5000mAh']],
  },
  {
    id: 'macbook-air-m2',
    name: 'MacBook Air 13" M2',
    brand: 'Apple',
    category: 'laptops',
    price: 1650000,
    stock: 4,
    icon: ICONS.deviceLaptop,
    blurb: 'Thin, silent and fast — the M2 chip handles everyday work and creative tasks with ease.',
    specs: [['Display', '13.6" Liquid Retina'], ['Chip', 'Apple M2'], ['Memory', '8GB unified'], ['Storage', '256GB SSD'], ['Battery', 'Up to 18h']],
  },
  {
    id: 'macbook-pro-14',
    name: 'MacBook Pro 14" M3',
    brand: 'Apple',
    category: 'laptops',
    price: 2450000,
    stock: 3,
    icon: ICONS.deviceLaptop,
    blurb: 'Pro-level performance for video editing, development and heavier creative workloads.',
    specs: [['Display', '14.2" Liquid Retina XDR'], ['Chip', 'Apple M3 Pro'], ['Memory', '18GB unified'], ['Storage', '512GB SSD'], ['Battery', 'Up to 18h']],
  },
  {
    id: 'apple-watch-series-9',
    name: 'Apple Watch Series 9',
    brand: 'Apple',
    category: 'wearables',
    price: 495000,
    stock: 8,
    icon: ICONS.deviceWatch,
    blurb: 'Advanced health tracking, a brighter always-on display and a faster S9 chip.',
    specs: [['Case', '45mm aluminum'], ['Display', 'Always-on Retina'], ['Health', 'ECG, blood oxygen'], ['Water resistance', '50m'], ['Battery', 'Up to 18h']],
  },
  {
    id: 'apple-watch-se',
    name: 'Apple Watch SE',
    brand: 'Apple',
    category: 'wearables',
    price: 320000,
    stock: 11,
    icon: ICONS.deviceWatch,
    blurb: 'The essentials of Apple Watch — activity tracking, notifications and safety features.',
    specs: [['Case', '40mm aluminum'], ['Display', 'Retina LTPO OLED'], ['Health', 'Heart rate, sleep tracking'], ['Water resistance', '50m'], ['Battery', 'Up to 18h']],
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro (2nd gen)',
    brand: 'Apple',
    category: 'audio',
    price: 285000,
    stock: 16,
    icon: ICONS.deviceEarbuds,
    blurb: 'Active noise cancellation, adaptive audio and a USB-C charging case.',
    specs: [['Type', 'In-ear, active noise cancelling'], ['Chip', 'Apple H2'], ['Case', 'USB-C, MagSafe'], ['Battery', 'Up to 6h, 30h with case'], ['Water resistance', 'IP54']],
  },
  {
    id: 'airpods-4',
    name: 'AirPods 4',
    brand: 'Apple',
    category: 'audio',
    price: 195000,
    stock: 18,
    icon: ICONS.deviceEarbuds,
    blurb: 'A refined open-ear fit with clearer calls and Apple\u2019s spatial audio.',
    specs: [['Type', 'In-ear'], ['Chip', 'Apple H2'], ['Case', 'USB-C'], ['Battery', 'Up to 5h, 30h with case'], ['Water resistance', 'IP54']],
  },
  {
    id: 'jbl-boombox-3',
    name: 'JBL Boombox 3',
    brand: 'JBL',
    category: 'audio',
    price: 385000,
    stock: 7,
    icon: ICONS.deviceSpeaker,
    blurb: 'A powerful portable speaker built for all-day outdoor sound with a rugged, waterproof build.',
    specs: [['Output', '180W'], ['Battery', 'Up to 24h'], ['Water resistance', 'IP67'], ['Connectivity', 'Bluetooth 5.1'], ['Extras', 'PartyBoost pairing']],
  },
  {
    id: 'over-ear-anc-headphones',
    name: 'Over-Ear ANC Headphones',
    brand: 'Generic',
    category: 'audio',
    price: 135000,
    stock: 22,
    icon: ICONS.deviceHeadphones,
    blurb: 'Comfortable over-ear headphones with active noise cancellation and a 30-hour battery.',
    specs: [['Type', 'Over-ear, closed-back'], ['Noise cancelling', 'Active (ANC)'], ['Battery', 'Up to 30h'], ['Connectivity', 'Bluetooth 5.2'], ['Extras', 'Foldable design']],
  },
  {
    id: 'watch-strap-set',
    name: 'Silicone Watch Strap Set (3-pack)',
    brand: 'Generic',
    category: 'accessories',
    price: 28000,
    stock: 30,
    icon: ICONS.deviceWatch,
    blurb: 'Three interchangeable silicone bands compatible with most 40mm/44mm smartwatch cases.',
    specs: [['Material', 'Soft silicone'], ['Compatibility', '40mm / 44mm case'], ['Included', '3 colors per pack'], ['Care', 'Wipe clean'], ['Fit', 'Adjustable']],
  },
  {
    id: 'fast-charger-65w',
    name: '65W USB-C Fast Charger',
    brand: 'Generic',
    category: 'accessories',
    price: 32000,
    stock: 40,
    icon: ICONS.devicePhone,
    blurb: 'A compact GaN charger that fast-charges phones, tablets and light laptops from one port.',
    specs: [['Output', '65W max'], ['Ports', '1x USB-C'], ['Tech', 'GaN, compact form'], ['Compatibility', 'Phones, tablets, ultrabooks'], ['Included', 'Charger only, cable sold separately']],
  },
  {
    id: 'tempered-glass-pack',
    name: 'Tempered Glass Screen Protector (2-pack)',
    brand: 'Generic',
    category: 'accessories',
    price: 12000,
    stock: 60,
    icon: ICONS.devicePhone,
    blurb: 'Case-friendly 9H tempered glass with an oleophobic coating to resist smudges.',
    specs: [['Hardness', '9H tempered glass'], ['Coating', 'Oleophobic, anti-smudge'], ['Included', '2 pieces + cleaning kit'], ['Fit', 'Edge-to-edge'], ['Install', 'Bubble-free application']],
  },
  {
    id: 'ipad-10th-gen',
    name: 'iPad (10th generation)',
    brand: 'Apple',
    category: 'accessories',
    price: 560000,
    stock: 0,
    icon: ICONS.deviceTablet,
    blurb: 'A colorful, capable everyday tablet for browsing, streaming and light creative work.',
    specs: [['Display', '10.9" Liquid Retina'], ['Chip', 'A14 Bionic'], ['Storage', '64GB'], ['Camera', '12MP wide'], ['Battery', 'Up to 10h']],
  },
];

function findProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}

function formatNaira(amount) {
  return '\u20a6' + amount.toLocaleString('en-NG');
}
